### ISSUE TITLE
版权相关

### ISSUE THREAD

**Issue by limingxinleo** [hyperf/xxl-job-incubator#1]
@tw2066 这个组件，有借鉴其他组件么？

**Comment by tw2066** [comment]
借鉴参数 接收类 Requests目录 里面文件
其余都是根据xxljob官方文档和java客户端写的

**Comment by tw2066** [comment]
https://github.com/HBLong/php-xxljob

**Comment by tw2066** [comment]
只看过HBLong/php-xxljob 项目
其余都是根据xxljob官方文档和java客户端写的

**Comment by huangzhhui** [comment]
是否有使用到其他项目的代码呢？

**Comment by limingxinleo** [comment]
@huangzhhui 我大体看了下，设计到 xxl 的就只有 request 目录里拿几个文件

其他的设计全都是 Hyperf 的设计风格

**Comment by tw2066** [comment]
是的，其他都是hyperf风格
